name: CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  main:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.20.x
      - uses: actions/checkout@v3
      - run: sudo apt-get update && sudo apt-get install -y libnetfilter-queue-dev
      - run: go test -exec sudo -covermode=atomic -race -v ./...
# TODO: enable golangci-lint
#      - name: golangci-lint
#        uses: golangci/golangci-lint-action@v3.4.0
#        with:
#          version: v1.51.2
#          args: --verbose
